Repository AY2223S2-CS2103T-W09-1/tp, pull requests merged in 2023-03, with the labels that each got.

#72 Update mr-teal.md
  docs/team/mr-teal.md
Labels: type.documentation

#74 Update DG and AboutUs.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.documentation

#77 Remove placeholder text in AboutUs.md
  docs/AboutUs.md
Labels: type.documentation

#92 Add v1.2 working version
  build.gradle
  src/main/java/seedu/recipe/MainApp.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/storage/JsonAdaptedStep.java
  src/main/java/seedu/recipe/storage/JsonSerializableRecipeBook.java
Labels: priority.High

#109 Update developer guide and modelclassdiagram
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
Labels: priority.Medium, type.documentation

#116 Update Logic part in DG.
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.documentation

#118 Edit Ui Component section in DG
  docs/DeveloperGuide.md
Labels: type.documentation

#135 Create tag function
  src/main/java/seedu/recipe/logic/commands/EditCommand.java
  src/main/java/seedu/recipe/logic/parser/AddCommandParser.java
  src/main/java/seedu/recipe/logic/parser/CliSyntax.java
  src/main/java/seedu/recipe/logic/parser/EditCommandParser.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/tag/Tag.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonAdaptedRecipe.java
  src/main/java/seedu/recipe/storage/JsonAdaptedTag.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipesRecipeBook.json
  src/test/java/seedu/recipe/logic/LogicManagerTest.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeUtil.java
  src/test/java/seedu/recipe/testutil/TypicalRecipes.java
Labels: type.Task, priority.High

#143 Fix UI
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeDetailsPanel.java
  src/main/resources/view/RecipeDetailsPanel.fxml
Labels: type.Bug

#146 Update ug
  docs/UserGuide.md
  docs/images/UiLandingPage.png
  docs/index.md
Labels: type.documentation

#150 Update UG
  docs/UserGuide.md
Labels: type.documentation

#147 Add price to ingredient and recipes, filter recipes by price condition
  bin/main/seedu/recipe/model/recipe/exceptions/DuplicateRecipeException.class
  bin/test/seedu/recipe/logic/LogicManagerTest.class
  bin/test/seedu/recipe/logic/commands/CommandTestUtil.class
  bin/test/seedu/recipe/logic/commands/EditRecipeDescriptorTest.class
  bin/test/seedu/recipe/logic/commands/FindCommandTest.class
  bin/test/seedu/recipe/logic/parser/AddCommandParserTest.class
  bin/test/seedu/recipe/logic/parser/AddressBookParserTest.class
  bin/test/seedu/recipe/logic/parser/EditCommandParserTest.class
  bin/test/seedu/recipe/logic/parser/ParserUtilTest.class
  bin/test/seedu/recipe/model/RecipeBookTest.class
  bin/test/seedu/recipe/model/recipe/RecipeTest.class
  bin/test/seedu/recipe/model/recipe/TitleContainsKeywordsPredicateTest.class
  bin/test/seedu/recipe/model/recipe/UniqueRecipeListTest.class
  bin/test/seedu/recipe/storage/StorageManagerTest.class
  bin/test/seedu/recipe/testutil/RecipeBuilder.class
  bin/test/seedu/recipe/testutil/RecipeUtil.class
  bin/test/seedu/recipe/testutil/TypicalRecipes.class
  src/main/java/seedu/recipe/MainApp.java
  src/main/java/seedu/recipe/logic/commands/FilterPriceCommand.java
  src/main/java/seedu/recipe/logic/parser/CookHubParser.java
  src/main/java/seedu/recipe/logic/parser/FilterPriceCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/model/RecipeBook.java
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/IngredientsContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/main/java/seedu/recipe/model/recipe/RecipeContainsKeywordsPredicate.java
  src/main/java/seedu/recipe/model/recipe/RecipeIngredientsSubsetPredicate.java
  src/main/java/seedu/recipe/model/recipe/SatisfyPriceConditionPredicate.java
  src/main/java/seedu/recipe/model/util/SampleDataUtil.java
  src/main/java/seedu/recipe/storage/JsonAdaptedIngredient.java
  src/main/java/seedu/recipe/storage/StorageManager.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeDetailsPanel.java
  src/test/data/JsonSerializableRecipeBookTest/duplicateRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/invalidRecipeRecipeBook.json
  src/test/data/JsonSerializableRecipeBookTest/typicalRecipesRecipeBook.json
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/recipe/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/recipe/logic/parser/ParserUtilTest.java
  src/test/java/seedu/recipe/model/recipe/IngredientTest.java
  src/test/java/seedu/recipe/model/recipe/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/recipe/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/recipe/storage/JsonAdaptedRecipeTest.java
  src/test/java/seedu/recipe/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeBuilder.java
  src/test/java/seedu/recipe/testutil/RecipeUtil.java
Labels: priority.High

#156 Change UG since ingredients changed
  docs/UserGuide.md
Labels: type.documentation

#158 Implemented get groceries feature
  src/main/java/seedu/recipe/logic/commands/GroceriesCommand.java
  src/main/java/seedu/recipe/logic/parser/CookHubParser.java
  src/main/java/seedu/recipe/logic/parser/GroceriesCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
Labels: priority.High

#163 Fix regex
  src/main/java/seedu/recipe/model/recipe/Description.java
  src/main/java/seedu/recipe/model/recipe/Step.java
  src/test/java/seedu/recipe/logic/commands/CommandTestUtil.java
Labels: priority.Medium
