Repository AY2223S2-CS2103T-W09-1/tp, pull requests merged in 2023-04, with the labels that each got.

#164 Add command result pictures. Categorize commands.
  docs/UserGuide.md
  docs/images/AddError.png
  docs/images/AddResult1.png
  docs/images/AddResult2.png
  docs/images/AllRecipesStarred.png
  docs/images/ClearResult.png
  docs/images/DeleteResult1.png
  docs/images/DeleteResult2.png
  docs/images/EditError.png
  docs/images/EditResult1.png
  docs/images/EditResult2.png
  docs/images/FavoritesResult.png
  docs/images/FindError1.png
  docs/images/FindError2.png
  docs/images/FindResult.png
  docs/images/FpResult.png
  docs/images/ListResult.png
  docs/images/OnlyError.png
  docs/images/OnlyResult1.png
  docs/images/OnlyResult2.png
  docs/images/SortResult.png
  docs/images/StarResult1.png
  docs/images/StarResult2.png
  docs/images/UiInWindows.png
  docs/images/UnstarResult1.png
  docs/images/UnstarResult2.png
  docs/images/helpMessage.png
Labels: type.documentation

#212 Make the language more livelier, change some of the command formats
  docs/UserGuide.md
Labels: type.documentation

#218 Fix functionality bugs from PE-d.
  docs/UserGuide.md
  src/main/java/seedu/recipe/MainApp.java
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/ui/RecipeCard.java
  src/main/java/seedu/recipe/ui/RecipeDetailsPanel.java
  src/main/resources/view/RecipeListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug

#220 Change project name
  docs/team/germainelee02.md
Labels: type.documentation

#223 Update Mr-Teal's PPP
  docs/team/mr-teal.md
Labels: type.documentation

#225 Replace line 8 of the DG Planned Enhancements
  docs/DeveloperGuide.md
Labels: type.documentation

#224 Bug fix branch
  src/main/java/seedu/recipe/logic/parser/FindCommandParser.java
  src/main/java/seedu/recipe/logic/parser/ParserUtil.java
  src/main/java/seedu/recipe/model/recipe/Recipe.java
  src/test/java/seedu/recipe/logic/parser/FindCommandParserTest.java
Labels: type.Bug, priority.High

#228 Update PPP
  docs/team/bernicetoh.md
Labels: type.documentation

#229 Update links in PPP
  docs/team/bernicetoh.md
Labels: type.documentation

#235 Add UG images
  docs/UserGuide.md
  docs/images/Logo.svg
  docs/images/annotated/addCommand.svg
  docs/images/annotated/deleteCommand.svg
  docs/images/annotated/editCommand.svg
  docs/images/annotated/findCommand.svg
  docs/images/annotated/starCommand.svg
Labels: type.documentation

#236 Ug update
  docs/UserGuide.md
  docs/images/Logo.svg
  docs/images/annotated/addCommand.svg
  docs/images/annotated/deleteCommand.svg
  docs/images/annotated/editCommand.svg
  docs/images/annotated/findCommand.svg
  docs/images/annotated/fpCommand.svg
  docs/images/annotated/groceriesCommand.svg
  docs/images/annotated/sortCommand.svg
  docs/images/annotated/starCommand.svg
  docs/images/annotated/unstarCommand.svg
Labels: type.documentation

#226 Modify error messages to follow UG
  docs/UserGuide.md
  src/main/java/seedu/recipe/logic/commands/AddCommand.java
  src/main/java/seedu/recipe/logic/commands/DeleteCommand.java
  src/main/java/seedu/recipe/logic/commands/EditCommand.java
  src/main/java/seedu/recipe/logic/commands/FavoritesCommand.java
  src/main/java/seedu/recipe/logic/commands/FilterPriceCommand.java
  src/main/java/seedu/recipe/logic/commands/FindCommand.java
  src/main/java/seedu/recipe/logic/commands/GroceriesCommand.java
  src/main/java/seedu/recipe/logic/commands/OnlyCommand.java
  src/main/java/seedu/recipe/logic/commands/SortCommand.java
  src/main/java/seedu/recipe/logic/commands/StarCommand.java
  src/main/java/seedu/recipe/logic/commands/UnstarCommand.java
  src/main/java/seedu/recipe/model/recipe/Description.java
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
  src/main/java/seedu/recipe/model/recipe/Step.java
  src/main/java/seedu/recipe/model/recipe/Title.java
Labels: type.Bug

#237 Increase size of images in UG
  docs/UserGuide.md
Labels: type.documentation

#240 Add CLI tutorial to UG
  docs/UserGuide.md
Labels: type.documentation

#243 Add annotated GUI to UG
  docs/UserGuide.md
  docs/images/annotated/GUI.svg
Labels: type.documentation

#244 User docs update
  docs/images/annotated/GUI.svg
  docs/team/bernicetoh.md
Labels: type.documentation

#248 Fix rounding bug and update the UG
  docs/UserGuide.md
  src/main/java/seedu/recipe/model/recipe/Ingredient.java
Labels: type.Bug, type.documentation

#249 As decimal points issue is resolved, example pictures in ug are changed.
  docs/UserGuide.md
  docs/images/AddError.png
  docs/images/AddResult1.png
  docs/images/AddResult2.png
  docs/images/AllRecipesStarred.png
  docs/images/DeleteError.png
  docs/images/DeleteResult.png
  docs/images/DeleteResult1.png
  docs/images/DeleteResult2.png
  docs/images/EditError.png
  docs/images/EditResult1.png
  docs/images/EditResult2.png
  docs/images/FavoritesResult.png
  docs/images/FindError1.png
  docs/images/FindError2.png
  docs/images/FindResult.png
  docs/images/FpResult.png
  docs/images/ListResult.png
  docs/images/OnlyError.png
  docs/images/OnlyResult2.png
  docs/images/SortResult.png
  docs/images/StarResult1.png
  docs/images/StarResult2.png
  docs/images/UiInWindows.png
  docs/images/UnstarResult1.png
  docs/images/UnstarResult2.png
Labels: type.documentation

#250 Update user docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/annotated/GUI.svg
Labels: type.documentation

#257 DG update
  docs/DeveloperGuide.md
Labels: type.documentation

#252 Update DG Implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/OnlySequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/OnlyCommandSequenceDiagram.png
Labels: type.documentation

#259 Update user docs again
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation

#262 Update DG part of PPP
  docs/team/germainelee02.md
Labels: type.documentation

#263 Update user docs again
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/annotated/GUI.png
Labels: type.documentation

#265 Attempt 1 at squeezing PPP to 2 pages
  docs/team/germainelee02.md
Labels: type.documentation

#261 Improve the UML sequence diagrams for add, find and only to be better
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/OnlySequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/OnlySequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  src/main/java/seedu/recipe/logic/parser/OnlyCommandParser.java
Labels: type.documentation

#267 Last update to PPP
  docs/team/bernicetoh.md
Labels: type.documentation

#268 Attempt 2 at shortening my PPP
  docs/team/germainelee02.md
Labels: type.documentation

#271 Annotate Ui images in UG
  docs/UserGuide.md
  docs/images/AddError.png
  docs/images/AddResult1.png
  docs/images/AddResult2.png
  docs/images/ClearResult.png
  docs/images/DeleteError.png
  docs/images/DeleteResult.png
  docs/images/EditError.png
  docs/images/EditResult1.png
  docs/images/EditResult2.png
  docs/images/FavoritesResult.png
  docs/images/FindError1.png
  docs/images/FindError2.png
  docs/images/FindResult.png
  docs/images/FpResult.png
  docs/images/GroceriesResult.png
  docs/images/ListResult.png
  docs/images/OnlyError.png
  docs/images/OnlyResult1.png
  docs/images/OnlyResult2.png
  docs/images/SortResult.png
  docs/images/StarResult2.png
  docs/images/UnstarResult2.png
Labels: type.documentation

#272 Modify DG
  docs/DeveloperGuide.md
  docs/diagrams/FavoritesSequenceDiagram.puml
  docs/diagrams/StarSequenceDiagram.puml
  docs/images/FavoritesSequenceDiagram.png
  docs/images/StarSequenceDiagram.png
Labels: type.documentation

#285 Final update for Mr-Teal's PPP.
  docs/team/mr-teal.md
Labels: type.documentation

#286 Final change to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation

#288 Final change to DG
  docs/DeveloperGuide.md
Labels: type.documentation

#287 Fix Planned Enhancements for DG
  docs/DeveloperGuide.md
Labels: type.documentation

#294 Modify UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StarSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/EditResult2.png
  docs/images/StarSequenceDiagram.png
Labels: type.documentation
